### ISSUE TITLE
How can i use SelectorBuilder (where) as filter query in mongo_db_driver package ?

### ISSUE THREAD

**Issue by Omar-IDOUDAOUD** [mongo-dart/mongo_db_driver#3]
void getFilteredData() async {
  final client = MongoClient(url);
  await client.connect();
  final db = client.db(dbName: 'productsDatabase');
  final collection = db.collection('products');
  final data = await collection
      .find(
        filter: where.gte('views', 50),
      )
      .toList();
  print(data); // It prints all collection documents, just like there is no filter query.
}

**Comment by giorgiofran** [comment]
check this for [example](https://github.com/mongo-dart/mongo_db_driver/blob/main/example/crud/find/find_one.dart)

In general you should use the mongo_db_query package instead of mongo_dart_query.

You can anyway use the Selector Builder, but you have to transform it in a document (Map) and pass the Map to the filter parameter.
